services:
  db:
    container_name: db
    image: postgres:15
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    ports:
      - 5433:5432

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    container_name: fastapi-app
    env_file:
      - .env
    ports:
      - 8000:8000
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host=0.0.0.0 --port=8000"
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
    container_name: celery_app
    env_file:
      - .env
    command: ["/python_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: flower_app
    env_file:
      - .env
    command: ["/python_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555


volumes:
  pgdbdata: