"""added roles

Revision ID: a95d6a137d6d
Revises: c0271b2b6713
Create Date: 2023-11-30 19:22:23.015532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95d6a137d6d'
down_revision: Union[str, None] = 'c0271b2b6713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)
    op.add_column('users', sa.Column('role', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('currencies', 'rate',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
