"""added users

Revision ID: c0271b2b6713
Revises: 5645c69fb6f8
Create Date: 2023-11-30 15:28:56.771563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0271b2b6713'
down_revision: Union[str, None] = '5645c69fb6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hashed', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.alter_column('currencies', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'rate',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('users')
    # ### end Alembic commands ###
